apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.pdp }}
  labels:
    app: {{ .Values.global.pdp }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.global.pdp }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.pdp }}
    spec:
      containers:
      - name: {{ .Values.global.pdp }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        image: {{ .Values.image.image }}
        resources:
          requests:
            memory: {{ .Values.requests.serviceMemory }}
            cpu: {{ .Values.requests.serviceCpu }}
        livenessProbe:
          httpGet:
            path: /oxauth/.well-known/openid-configuration
            port: 8080
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
        readinessProbe:
          httpGet:
            path: /oxauth/.well-known/openid-configuration
            port: 8080
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
        ports:
        - name: http-pdp
          containerPort: 5567
          protocol: TCP
        - name: https-pdp
          containerPort: 443
          protocol: TCP
        envFrom:
        - configMapRef:
            name: um-pdp-engine-config
      - name: mongo
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        image: mongo
        resources:
          requests:
            memory: {{ .Values.requests.dbMemory }}
            cpu: {{ .Values.requests.dbCpu }}
        ports:
        - name: http-rp
          containerPort: 27017
          protocol: TCP
        envFrom:
        - configMapRef:
            name: um-pdp-engine-config
        volumeMounts:
        - mountPath: /data/db/
          subPath: {{ .Values.global.pdp }}/data/db
          name: {{ .Values.volumeClaim.name }}
      hostAliases:
      - ip: {{ .Values.global.nginxIp }}
        hostnames:
        - {{ .Values.global.ep }}
      volumes:
        - name: {{ .Values.volumeClaim.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volumeClaim.name }}