# Default values for pdp-engine.

global:
  namespace: default
  ep: demoexample.gluu.org
  domain:  http://demoexample.gluu.org
  pdp: pdp-engine
  auth_server_url: http://demoexample.gluu.org
  prefix: /
  host: 0.0.0.0
  port: 5567
  check_ssl_certs: "'false'"
  debug_mode: "'true'"
  nginxIp: 10.0.2.15

readinessProbe:
  initialDelaySeconds: 150
  periodSeconds: 90
livenessProbe:
  initialDelaySeconds: 150
  periodSeconds: 90

# limits:
#   memory: 600Mi
requests:
  serviceCpu: 4m
  serviceMemory: 70Mi
  dbCpu: 2m
  dbMemory: 70Mi

image: 
  statefulSetReplicas: 1
  imagePullPolicy: Always
  image: eoepca/um-pdp-engine:v0.3
persistence: 
  accessModes: ReadWriteMany
  dbStorageSize: 5Gi
  type: DirectoryOrCreate

config:
  enabled: true

# VolumeClaim values
volumeClaim:
  name: um-pdp-engine-pvc
