# Default values for pdp-engine.

global:
  namespace: default
  ep: demoexample.gluu.org
  domain:  http://demoexample.gluu.org
  pdp: pdp-engine
  prefix: /
  host: 0.0.0.0
  port: 5567
  check_ssl_certs: "'false'"
  debug_mode: "'true'"
  nginxIp: 10.0.2.15

readinessProbe:
  initialDelaySeconds: 150
  periodSeconds: 90
livenessProbe:
  initialDelaySeconds: 150
  periodSeconds: 90

requests:
  serviceCpu: 4m
  serviceMemory: 70Mi
  dbCpu: 2m
  dbMemory: 70Mi

image: 
  imagePullPolicy: Never
  image: alvlpdp:latest
persistence: 
  accessModes: ReadWriteMany
  dbStorageSize: 5Gi
  type: DirectoryOrCreate

# VolumeClaim values
volumeClaim:
  name: um-pdp-engine-pvc

ports:
  http-pdp:
    port: 5567
    targetPort: 5567
    type: TCP
  https-pdp:
    port: 1025
    targetPort: 443
    type: TCP
