language: python
python: 3.6.9

env:
  DOCKER_COMPOSE_VERSION: 1.25.4
services:
  - docker

jobs:
  include:
    - stage: Testing Mongo
      install: pip install -r src/requirements.txt
      script: python3 -m unittest tests/test_database.py

    - stage: Testing PDP
      install: pip install -r src/requirements.txt
      before_script: cd tests
      script: python3 -m unittest um_pdp_test.py

    - stage: Static Code Analysis    
      language: java
      if: branch = develop
      before_install:
        - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
        - unzip sonar-scanner-cli-3.3.0.1492-linux.zip -d /tmp
      script: /tmp/sonar-scanner-3.3.0.1492-linux/bin/sonar-scanner -Dsonar.projectKey=$SONARQUBE_PROJECT_KEY -Dsonar.sources=. -Dsonar.host.url=$SONARQUBE_URL -Dsonar.login=$SONAR_TOKEN


    - stage: container creation and publishing
      install: skip
      script: travis/containerCreation.sh um-pdp-engine

    - stage: smoke and acceptance test
      install: skip # without this there's a `git clone` executed!
      script: travis/acceptanceTest.sh um-pdp-engine 8080 7000 # Service name + external port + internal port for docker

    - stage: release
      if: branch = master AND NOT type IN (pull_request)
      install: skip
      script: travis/release.sh um-pdp-engine

import:
  - docs/.travis.yml

#notifications:
#  slack: eoepca:Msk9hjQKAbwSYcVWiepenPim
#  email:
#    recipients:
#      - a.person@acme.com
#      - a.n.other@acme.com
#    on_success: never # default: change
#    on_failure: never # default: always
